// src/lib/mock-data/news.ts
// Static ISO dates — NO dynamic date functions (fixes React hydration error)

import type { NewsItem } from "../types";

export const MOCK_NEWS: NewsItem[] = [
  {
    id: "news-001",
    headline: "⚠ Cade Cunningham (collapsed lung) officially OUT vs Pelicans — Daniss Jenkins to start",
    summary: "Cunningham will be re-evaluated in 2 weeks per the Pistons. He's averaging 24.5 PPG and 9.9 APG (2nd in NBA). Daniss Jenkins enters the starting lineup. The line has already moved but model finds NOP +3.5 still carries value.",
    source: "ESPN",
    url: "#",
    sport: "NBA",
    tags: ["Cade Cunningham", "Detroit Pistons", "New Orleans Pelicans"],
    sentiment: "injury_concern",
    signals: { injuryFlag: true, usageFlag: false, momentumFlag: false, fatigueFlag: false, publicHype: false },
    publishedAt: new Date().toISOString().slice(0,10) + "T09:00:00.000Z",
  },
  {
    id: "news-002",
    headline: "Trey Murphy III averaging 34.7 PPG over last 3 games — hottest scorer in NBA",
    summary: "Murphy has averaged 34.7 points over his last three games to raise his season average to 21.7 PPG. With Cunningham out in Detroit, Murphy and Zion Williamson (22.8 PPG) give the Pelicans a dangerous offensive duo on the road.",
    source: "The Athletic",
    url: "#",
    sport: "NBA",
    tags: ["Trey Murphy III", "New Orleans Pelicans"],
    sentiment: "positive",
    signals: { injuryFlag: false, usageFlag: true, momentumFlag: true, fatigueFlag: false, publicHype: true },
    publishedAt: new Date().toISOString().slice(0,10) + "T08:30:00.000Z",
  },
  {
    id: "news-003",
    headline: "Franz Wagner (ankle) misses 17th straight — Magic hobbled vs Kings tonight",
    summary: "Wagner remains out with no timetable for return from a high ankle sprain. Jalen Suggs (illness) and Anthony Black (abdomen) are also out. Desmond Bane will carry the offensive load — he's averaging 21.8 PPG over his last 9 games.",
    source: "CBS Sports",
    url: "#",
    sport: "NBA",
    tags: ["Franz Wagner", "Orlando Magic", "Sacramento Kings"],
    sentiment: "injury_concern",
    signals: { injuryFlag: true, usageFlag: false, momentumFlag: false, fatigueFlag: false, publicHype: false },
    publishedAt: new Date().toISOString().slice(0,10) + "T10:00:00.000Z",
  },
  {
    id: "news-004",
    headline: "March Madness Sweet 16: Four elite matchups today — model finds UNDER value on all four totals",
    summary: "Arizona (34-2) vs Arkansas, Purdue vs Texas, Houston vs Illinois, and Nebraska vs Iowa make up today's Sweet 16 slate. Model projects all four totals to finish below the line, with the Houston-Illinois UNDER (140.5) offering 3.7 points of value.",
    source: "AlphaEdge Model",
    url: "#",
    sport: "NCAAMB",
    tags: ["NCAA Tournament", "Sweet 16", "Arizona", "Houston", "Purdue"],
    sentiment: "neutral",
    signals: { injuryFlag: false, usageFlag: false, momentumFlag: false, fatigueFlag: false, publicHype: false },
    publishedAt: new Date().toISOString().slice(0,10) + "T11:00:00.000Z",
  },
  {
    id: "news-005",
    headline: "Brunson and KAT road test vs LaMelo and Hornets — tight pick-em tonight",
    summary: "Charlotte is a -1.5 home favorite vs the Knicks in what the model calls a near coin-flip. Brunson has been averaging 26.4 PPG over his last 5 with KAT healthy. LaMelo Ball's scoring creates problems for NYK's backcourt.",
    source: "ESPN",
    url: "#",
    sport: "NBA",
    tags: ["Jalen Brunson", "New York Knicks", "Charlotte Hornets", "LaMelo Ball"],
    sentiment: "neutral",
    signals: { injuryFlag: false, usageFlag: false, momentumFlag: true, fatigueFlag: false, publicHype: false },
    publishedAt: new Date().toISOString().slice(0,10) + "T07:00:00.000Z",
  },
  {
    id: "news-006",
    headline: "MLB Opening Week: Dodgers host Diamondbacks as -286 massive favorites tonight",
    summary: "Los Angeles hosts Arizona in a rematch of recent playoff series. LAD -286 at Dodger Stadium is among the heaviest lines of the early season. Model confirms fair value but finds slight UNDER value at 8.3 vs the 8.5 total.",
    source: "MLB.com",
    url: "#",
    sport: "MLB",
    tags: ["Los Angeles Dodgers", "Arizona Diamondbacks"],
    sentiment: "neutral",
    signals: { injuryFlag: false, usageFlag: false, momentumFlag: false, fatigueFlag: false, publicHype: false },
    publishedAt: new Date().toISOString().slice(0,10) + "T12:00:00.000Z",
  },
  {
    id: "news-007",
    headline: "Arizona Wildcats (34-2) enter Sweet 16 as West Region favorite — 1-seed dominance expected",
    summary: "Arizona is one of the national title favorites entering Thursday's Sweet 16 matchup vs Arkansas. The 34-2 record is among the best in the country. Model projects Arizona -8.2 (aligns with -7.5 line) and finds UNDER 164.5 as the key value play.",
    source: "CBS Sports",
    url: "#",
    sport: "NCAAMB",
    tags: ["Arizona Wildcats", "Arkansas Razorbacks", "Sweet 16"],
    sentiment: "positive",
    signals: { injuryFlag: false, usageFlag: false, momentumFlag: true, fatigueFlag: false, publicHype: true },
    publishedAt: new Date().toISOString().slice(0,10) + "T06:00:00.000Z",
  },
];
