// src/lib/mock-data/players.ts
import type { Player } from "../types";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "jayson-tatum",
    name: "Jayson Tatum",
    position: "SF",
    number: "0",
    sport: "NBA",
    status: "active",
    team: {
      id: "bos",
      name: "Boston Celtics",
      shortName: "Celtics",
      abbreviation: "BOS",
      city: "Boston",
      sport: "NBA",
      record: "52-18",
    },
    imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
    seasonAverages: {
      points: 26.9,
      rebounds: 8.1,
      assists: 4.9,
      minutesPerGame: 36.2,
      usageRate: 30.1,
    },
  },
  {
    id: "nikola-jokic",
    name: "Nikola Jokić",
    position: "C",
    number: "15",
    sport: "NBA",
    status: "active",
    team: {
      id: "den",
      name: "Denver Nuggets",
      shortName: "Nuggets",
      abbreviation: "DEN",
      city: "Denver",
      sport: "NBA",
      record: "46-24",
    },
    seasonAverages: {
      points: 26.4,
      rebounds: 12.3,
      assists: 9.1,
      minutesPerGame: 34.8,
      usageRate: 27.6,
    },
  },
  {
    id: "jalen-brunson",
    name: "Jalen Brunson",
    position: "PG",
    number: "11",
    sport: "NBA",
    status: "questionable",
    team: {
      id: "nyc",
      name: "New York Knicks",
      shortName: "Knicks",
      abbreviation: "NYK",
      city: "New York",
      sport: "NBA",
      record: "43-27",
    },
    seasonAverages: {
      points: 28.7,
      rebounds: 3.6,
      assists: 6.7,
      minutesPerGame: 35.6,
      usageRate: 34.2,
    },
  },
  {
    id: "aaron-judge",
    name: "Aaron Judge",
    position: "RF",
    number: "99",
    sport: "MLB",
    status: "active",
    team: {
      id: "nyy",
      name: "New York Yankees",
      shortName: "Yankees",
      abbreviation: "NYY",
      city: "New York",
      sport: "MLB",
      record: "22-14",
    },
    seasonAverages: {
      battingAverage: 0.292,
      homeRuns: 18,
      rbi: 52,
      obp: 0.418,
      slg: 0.621,
    },
  },
  {
    id: "cooper-flagg",
    name: "Cooper Flagg",
    position: "SF/PF",
    number: "2",
    sport: "NCAAMB",
    status: "active",
    team: {
      id: "duk",
      name: "Duke Blue Devils",
      shortName: "Duke",
      abbreviation: "DUKE",
      city: "Durham",
      sport: "NCAAMB",
      record: "27-6",
    },
    seasonAverages: {
      points: 19.2,
      rebounds: 8.1,
      assists: 4.2,
      minutesPerGame: 32.4,
    },
  },
  {
    id: "stephen-curry",
    name: "Stephen Curry",
    position: "PG",
    number: "30",
    sport: "NBA",
    status: "active",
    team: {
      id: "gsw",
      name: "Golden State Warriors",
      shortName: "Warriors",
      abbreviation: "GSW",
      city: "Golden State",
      sport: "NBA",
      record: "38-32",
    },
    seasonAverages: {
      points: 24.6,
      rebounds: 4.2,
      assists: 5.1,
      minutesPerGame: 32.7,
      usageRate: 28.9,
    },
  },
];
